name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # setup node version
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Install dependencies
      - name: Install NPM Packages
        run: npm install

      # Run test
      - name: Run test
        run: npm run test